version: '3.4'

volumes:
  postgres_data:

services:
  django:
    image: xiberty/sawi-api:latest
    depends_on:
      - postgres
      - redis
    env_file:
      - .envs/prod/django
      - .envs/prod/postgres

  postgres:
    env_file:
      - .envs/prod/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
