# Generated by Django 3.0.5 on 2020-06-01 08:56

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('specialty', models.CharField(choices=[('pediatrician', 'PEDIATRICIAN'), ('general_doctor', 'GENERAL DOCTOR')], default='general_doctor', max_length=25)),
                ('title', models.TextField(verbose_name='Title')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Locatión')),
                ('verified', models.BooleanField(default=False, verbose_name='Is verified?')),
                ('start_time', models.TimeField(verbose_name='Start')),
                ('end_time', models.TimeField(verbose_name='End')),
                ('fee', models.DecimalField(decimal_places=2, help_text='This price is for the a session wirh [x] duration in minutes, duration is configured below', max_digits=20, verbose_name='Fee')),
                ('consultation_duration', models.IntegerField(help_text='This time is in minutes', verbose_name='Consultation Duration')),
                ('auto_confirmation', models.BooleanField(default=True, help_text="If it's false the doctor must be accept or denied appointments manually", verbose_name='Auto Confirmation?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED'), ('DENIED', 'DENIED')], default='REQUESTED', max_length=50, verbose_name='Status')),
                ('site', models.CharField(choices=[('IN_PLACE', 'IN_PLACE'), ('ONLINE', 'ONLINE')], default='IN_PLACE', max_length=50, verbose_name='Site')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('consultation_duration', models.PositiveIntegerField(verbose_name='Duration')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='This field changes according to the type of action', verbose_name='extra')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.DoctorProfile', verbose_name='Doctor')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Visitor')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['created_at'],
                'unique_together': {('doctor', 'visitor', 'date', 'time')},
            },
        ),
    ]
