# Generated by Django 3.0.5 on 2020-05-25 07:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(verbose_name='Start')),
                ('end_time', models.TimeField(verbose_name='End')),
                ('duration', models.IntegerField(help_text='This time is in minutes', verbose_name='Duration')),
                ('auto_confirmation', models.BooleanField(default=True, verbose_name='Auto Confirmation?')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'db_table': 'agendas',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField(verbose_name='Day')),
                ('start_hour', models.IntegerField(verbose_name='Start Hour')),
                ('end_hour', models.IntegerField(verbose_name='Start Hour')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.Agenda')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED'), ('DENIED', 'DENIED')], default='REQUESTED', max_length=50, verbose_name='Status')),
                ('site', models.CharField(choices=[('IN_PLACE', 'IN_PLACE'), ('ONLINE', 'ONLINE')], default='IN_PLACE', max_length=50, verbose_name='Site')),
                ('start_datetime', models.DateTimeField(verbose_name='Start')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='This field changes according to the type of action', verbose_name='extra')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendas.Agenda', verbose_name='Agenda')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Visitor')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['created_at'],
            },
        ),
    ]
