# Generated by Django 3.0.5 on 2020-06-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_appointment_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='fee',
            field=models.DecimalField(decimal_places=2, help_text='This price is for the a session with [x] duration in minutes, duration is configured below', max_digits=20, verbose_name='Fee'),
        ),
    ]
